#!/bin/bash

#SBATCH --partition=cfdg.p
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8016
#SBATCH --gres=gpu:H100:4
#SBATCH --exclude=cfdg001
#SBATCH --time=02:30:00              # 2.5h — Phase 0g hit 1.5h timeout, give margin
#SBATCH --job-name=tactis_amax_sweep
#SBATCH --output=/dss/work/taed7566/Forecasting_Outputs/wind-forecasting/logs/slurm_logs/tactis_amax_sweep_%j.out
#SBATCH --error=/dss/work/taed7566/Forecasting_Outputs/wind-forecasting/logs/slurm_logs/tactis_amax_sweep_%j.err
#SBATCH --hint=nomultithread
#SBATCH --distribution=block:block
#SBATCH --gres-flags=enforce-binding

# =============================================================================
# TACTiS-2 PHASE 0g' — a_max threshold sweep
# =============================================================================
# Phase 0g found smooth a-cap (a_max) is the dominant v2 regularizer. F⁻¹ MEAN
# improved 20× over v1 with a_max=20, but F⁻¹ MEDIAN was still 0.038 (most
# contexts collapsed). Hypothesis: a tighter cap forces multiple hidden units
# to contribute, raising the median.
#
# 4 parallel single-GPU TRAINING runs:
#   GPU 0: a_max =  3.0   (very tight — may over-constrain capacity)
#   GPU 1: a_max =  5.0   (tight — Trial #65's max_a_pre was probably ~5)
#   GPU 2: a_max = 10.0   (moderate — clear separation from default)
#   GPU 3: a_max = 20.0   (current default — reproduces Phase 0g baseline)
#
# Same other hparams (Trial #65, lambda_a_reg=0.46, lambda_log_density=0.5,
# log_density_max=0.0). Per-worker YAML generated by sed-replacing __A_MAX__
# in base template.
#
# Submit:
#   eval "$(grep '^export LOCAL_PG_PASSWORD=' ~/.zshrc)"
#   sbatch --export=ALL,LOCAL_PG_PASSWORD tune_a_max_sweep.sh
# =============================================================================

export MODEL_NAME="tactis"

BASE_DIR="/user/taed7566/Forecasting/wind-forecasting"
OUTPUT_DIR="/dss/work/taed7566/Forecasting_Outputs/wind-forecasting"
export WORK_DIR="${BASE_DIR}/wind_forecasting"
export LOG_DIR="${OUTPUT_DIR}/logs"
export BASE_CONFIG="${BASE_DIR}/config/training/training_inputs_storm_awaken_smoothed_pred60_tactis_a_max_sweep_base.yaml"

export NUMEXPR_MAX_THREADS=128

mkdir -p ${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}
mkdir -p ${LOG_DIR}/checkpoints

GENERATED_CONFIGS_DIR="${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/generated_configs"
mkdir -p "${GENERATED_CONFIGS_DIR}"

cd ${WORK_DIR} || exit 1

export PYTHONPATH=${WORK_DIR}:/fs/dss/home/taed7566/Forecasting/pytorch-transformer-ts:${PYTHONPATH}
export WANDB_DIR=${LOG_DIR}

echo "=============================================="
echo "TACTiS-2 PHASE 0g' — a_max sweep"
echo "=============================================="
echo "JOB ID: ${SLURM_JOB_ID}"
echo "Sweep: a_max ∈ [3.0, 5.0, 10.0, 20.0]"
echo "Fixed: log_density_max=0.0, lambda_a_reg=0.46, lambda_log_density=0.5"
echo "Per-run budget: 15 epochs × 2000 batches × bs=64"
echo "=============================================="

module purge
module load slurm/hpc-2023/23.02.7
module load hpc-env/13.1
module load Mamba/24.3.0-0
module load CUDA/12.4.0
module load git
eval "$(conda shell.bash hook)"
conda activate wf_env_storm

if [ -z "${LOCAL_PG_PASSWORD:-}" ]; then
    echo "ERROR: LOCAL_PG_PASSWORD env var not set." >&2
    exit 1
fi
export PGPASSWORD="${LOCAL_PG_PASSWORD}"

A_MAX_VALUES=(3.0 5.0 10.0 20.0)
declare -a CONFIG_PATHS=()
for i in "${!A_MAX_VALUES[@]}"; do
    AMAX="${A_MAX_VALUES[$i]}"
    LABEL="$(echo "${AMAX}" | sed 's/\./p/g')"
    OUT_PATH="${GENERATED_CONFIGS_DIR}/a_max_${LABEL}.yaml"
    sed "s|__A_MAX__|${AMAX}|g" "${BASE_CONFIG}" > "${OUT_PATH}"
    CONFIG_PATHS+=("${OUT_PATH}")
    echo "Generated config for a_max=${AMAX}: ${OUT_PATH}"
done

echo "=== STARTING 4 PARALLEL TRAINING RUNS ==="
date +"%Y-%m-%d %H:%M:%S"

NUM_GPUS=${SLURM_NTASKS_PER_NODE}
declare -a WORKER_PIDS=()

for i in "${!A_MAX_VALUES[@]}"; do
    AMAX="${A_MAX_VALUES[$i]}"
    CONFIG_PATH="${CONFIG_PATHS[$i]}"

    echo "Launching worker ${i} on GPU ${i} with a_max=${AMAX}"

    CUDA_VISIBLE_DEVICES=${i} nohup bash -c "
        module purge
        module load slurm/hpc-2023/23.02.7
        module load hpc-env/13.1
        module load mpi4py/3.1.4-gompi-2023a
        module load Mamba/24.3.0-0
        module load CUDA/12.4.0
        module load git

        eval \"\$(conda shell.bash hook)\"
        conda activate wf_env_storm

        export PGPASSWORD=\"\${LOCAL_PG_PASSWORD}\"

        python ${WORK_DIR}/run_scripts/run_model.py \\
          --config ${CONFIG_PATH} \\
          --model ${MODEL_NAME} \\
          --mode train \\
          --seed 42 \\
          --single_gpu

        status=\$?
        if [ \$status -ne 0 ]; then
            echo \"Worker ${i} (a_max=${AMAX}) FAILED with status \$status\"
        else
            echo \"Worker ${i} (a_max=${AMAX}) COMPLETED successfully\"
        fi
        exit \$status
    " > "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/worker_${i}_amax${AMAX}_${SLURM_JOB_ID}.log" 2>&1 &

    WORKER_PIDS+=($!)
    sleep 2
done

while true; do
    ALIVE_WORKERS=0
    for pid in ${WORKER_PIDS[@]}; do
        if kill -0 $pid 2>/dev/null; then
            ((ALIVE_WORKERS++))
        fi
    done
    echo "$(date +"%Y-%m-%d %H:%M:%S") - Workers still running: ${ALIVE_WORKERS}/${#WORKER_PIDS[@]}"
    if [ $ALIVE_WORKERS -eq 0 ]; then
        echo "All workers have finished."
        break
    fi
    sleep 60
done

echo "--- Worker Completion Status ---"
FAILED_WORKERS=0
SUCCESSFUL_WORKERS=0
for i in "${!A_MAX_VALUES[@]}"; do
    AMAX="${A_MAX_VALUES[$i]}"
    WORKER_LOG="${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/worker_${i}_amax${AMAX}_${SLURM_JOB_ID}.log"
    if [ -f "$WORKER_LOG" ] && grep -q "COMPLETED successfully" "$WORKER_LOG"; then
        echo "Worker ${i} (a_max=${AMAX}): SUCCESS"
        ((SUCCESSFUL_WORKERS++))
    else
        echo "Worker ${i} (a_max=${AMAX}): FAILED or KILLED"
        ((FAILED_WORKERS++))
    fi
done

echo "=============================================="
echo "a_max SWEEP COMPLETE"
echo "Successful: ${SUCCESSFUL_WORKERS}/4"
echo "After: probe each manual_save_epoch9.ckpt for F⁻¹(U) std comparison"
echo "  (lower a_max should raise F⁻¹ median if hypothesis is correct)"
echo "=============================================="
date +"%Y-%m-%d %H:%M:%S"

for f in ${LOG_DIR}/slurm_logs/*_${SLURM_JOB_ID}.out; do
    [ -e "$f" ] && mv "$f" "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/" 2>/dev/null
done
for f in ${LOG_DIR}/slurm_logs/*_${SLURM_JOB_ID}.err; do
    [ -e "$f" ] && mv "$f" "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/" 2>/dev/null
done

exit $FAILED_WORKERS
