#!/bin/bash

#SBATCH --partition=cfdg.p
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4         # 4 H100 — one per threshold value
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8016
#SBATCH --gres=gpu:H100:4
#SBATCH --exclude=cfdg001
#SBATCH --time=01:30:00              # 4× 30-45min runs in parallel = ~45 min total wall
#SBATCH --job-name=tactis_logd_sweep
#SBATCH --output=/dss/work/taed7566/Forecasting_Outputs/wind-forecasting/logs/slurm_logs/tactis_logd_sweep_%j.out
#SBATCH --error=/dss/work/taed7566/Forecasting_Outputs/wind-forecasting/logs/slurm_logs/tactis_logd_sweep_%j.err
#SBATCH --hint=nomultithread
#SBATCH --distribution=block:block
#SBATCH --gres-flags=enforce-binding

# =============================================================================
# TACTiS-2 PHASE 0g — log_density_max threshold sweep
# =============================================================================
# 4 parallel single-GPU TRAINING runs (NOT Optuna), one per threshold value:
#   GPU 0: log_density_max = -2.0
#   GPU 1: log_density_max =  0.0
#   GPU 2: log_density_max =  1.0
#   GPU 3: log_density_max =  3.0
#
# All other hparams IDENTICAL across the 4 runs (Trial #65 winning + smoke
# v2 reg defaults). Any difference in metrics across runs is attributable to
# the threshold value alone — clean signal, no Optuna noise.
#
# Per-worker YAML is generated by sed-replacing __LOG_DENSITY_MAX__ in the base
# template. WandB run_name and chkp_dir_suffix include the threshold value, so
# all 4 runs are clearly separated in the WandB project.
#
# Compute: 15 epochs × 2000 batches × bs=64 = 1.92M samples per run.
# Wall: ~30-45 min on H100. 4 in parallel = ~30-45 min total.
#
# Submit:
#   eval "$(grep '^export LOCAL_PG_PASSWORD=' ~/.zshrc)"
#   sbatch --export=ALL,LOCAL_PG_PASSWORD tune_log_density_sweep.sh
# =============================================================================

export MODEL_NAME="tactis"

BASE_DIR="/user/taed7566/Forecasting/wind-forecasting"
OUTPUT_DIR="/dss/work/taed7566/Forecasting_Outputs/wind-forecasting"
export WORK_DIR="${BASE_DIR}/wind_forecasting"
export LOG_DIR="${OUTPUT_DIR}/logs"
export BASE_CONFIG="${BASE_DIR}/config/training/training_inputs_storm_awaken_smoothed_pred60_tactis_log_density_sweep_base.yaml"

export NUMEXPR_MAX_THREADS=128

mkdir -p ${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}
mkdir -p ${LOG_DIR}/checkpoints

# Per-worker YAML output dir — one config per threshold
GENERATED_CONFIGS_DIR="${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/generated_configs"
mkdir -p "${GENERATED_CONFIGS_DIR}"

cd ${WORK_DIR} || exit 1

export PYTHONPATH=${WORK_DIR}:/fs/dss/home/taed7566/Forecasting/pytorch-transformer-ts:${PYTHONPATH}
export WANDB_DIR=${LOG_DIR}

echo "=============================================="
echo "TACTiS-2 PHASE 0g — log_density_max sweep"
echo "=============================================="
echo "JOB ID: ${SLURM_JOB_ID}"
echo "PARTITION: ${SLURM_JOB_PARTITION}"
echo "NODE: ${SLURM_JOB_NODELIST}"
echo "BASE CONFIG: ${BASE_CONFIG}"
echo "Generated configs: ${GENERATED_CONFIGS_DIR}"
echo "----------------------------------------------"
echo "Sweep: log_density_max ∈ [-2.0, 0.0, 1.0, 3.0]"
echo "Fixed: lambda_a_reg=0.46, lambda_log_density=0.5, a_max=20"
echo "Per-run budget: 15 epochs × 2000 batches × bs=64"
echo "=============================================="
echo "Branch states:"
echo "  pytorch-transformer-ts: $(cd /fs/dss/home/taed7566/Forecasting/pytorch-transformer-ts && git rev-parse --abbrev-ref HEAD) @ $(cd /fs/dss/home/taed7566/Forecasting/pytorch-transformer-ts && git rev-parse --short HEAD)"
echo "  wind-forecasting:       $(cd ${BASE_DIR} && git rev-parse --abbrev-ref HEAD) @ $(cd ${BASE_DIR} && git rev-parse --short HEAD)"
echo "=============================================="

module purge
module load slurm/hpc-2023/23.02.7
module load hpc-env/13.1
module load Mamba/24.3.0-0
module load CUDA/12.4.0
module load git
eval "$(conda shell.bash hook)"
conda activate wf_env_storm

if [ -z "${LOCAL_PG_PASSWORD:-}" ]; then
    echo "ERROR: LOCAL_PG_PASSWORD env var not set." >&2
    exit 1
fi
export PGPASSWORD="${LOCAL_PG_PASSWORD}"

# Generate per-threshold YAMLs
THRESHOLDS=(-2.0 0.0 1.0 3.0)
declare -a CONFIG_PATHS=()
for i in "${!THRESHOLDS[@]}"; do
    THR="${THRESHOLDS[$i]}"
    # Make a filesystem-safe label (replace . with p, - with neg)
    LABEL="$(echo "${THR}" | sed 's/\./p/g; s/^-/neg/')"
    OUT_PATH="${GENERATED_CONFIGS_DIR}/log_density_thresh_${LABEL}.yaml"
    sed "s|__LOG_DENSITY_MAX__|${THR}|g" "${BASE_CONFIG}" > "${OUT_PATH}"
    CONFIG_PATHS+=("${OUT_PATH}")
    echo "Generated config for threshold=${THR}: ${OUT_PATH}"
done

echo "=== STARTING 4 PARALLEL TRAINING RUNS (1 per threshold) ==="
date +"%Y-%m-%d %H:%M:%S"

NUM_GPUS=${SLURM_NTASKS_PER_NODE}
declare -a WORKER_PIDS=()

for i in "${!THRESHOLDS[@]}"; do
    THR="${THRESHOLDS[$i]}"
    CONFIG_PATH="${CONFIG_PATHS[$i]}"

    echo "Launching worker ${i} on GPU ${i} with threshold=${THR}"

    CUDA_VISIBLE_DEVICES=${i} nohup bash -c "
        module purge
        module load slurm/hpc-2023/23.02.7
        module load hpc-env/13.1
        module load mpi4py/3.1.4-gompi-2023a
        module load Mamba/24.3.0-0
        module load CUDA/12.4.0
        module load git

        eval \"\$(conda shell.bash hook)\"
        conda activate wf_env_storm

        export PGPASSWORD=\"\${LOCAL_PG_PASSWORD}\"

        echo \"Worker ${i}: training with log_density_max=${THR}\"

        python ${WORK_DIR}/run_scripts/run_model.py \\
          --config ${CONFIG_PATH} \\
          --model ${MODEL_NAME} \\
          --mode train \\
          --seed 42 \\
          --single_gpu

        status=\$?
        if [ \$status -ne 0 ]; then
            echo \"Worker ${i} (threshold=${THR}) FAILED with status \$status\"
        else
            echo \"Worker ${i} (threshold=${THR}) COMPLETED successfully\"
        fi
        exit \$status
    " > "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/worker_${i}_thresh${THR}_${SLURM_JOB_ID}.log" 2>&1 &

    WORKER_PIDS+=($!)
    sleep 2
done

while true; do
    ALIVE_WORKERS=0
    for pid in ${WORKER_PIDS[@]}; do
        if kill -0 $pid 2>/dev/null; then
            ((ALIVE_WORKERS++))
        fi
    done

    echo "$(date +"%Y-%m-%d %H:%M:%S") - Workers still running: ${ALIVE_WORKERS}/${#WORKER_PIDS[@]}"

    if [ $ALIVE_WORKERS -eq 0 ]; then
        echo "All workers have finished."
        break
    fi
    sleep 60
done

echo "--- Worker Completion Status ---"
FAILED_WORKERS=0
SUCCESSFUL_WORKERS=0
for i in "${!THRESHOLDS[@]}"; do
    THR="${THRESHOLDS[$i]}"
    WORKER_LOG="${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/worker_${i}_thresh${THR}_${SLURM_JOB_ID}.log"
    if [ -f "$WORKER_LOG" ]; then
        if grep -q "COMPLETED successfully" "$WORKER_LOG"; then
            echo "Worker ${i} (threshold=${THR}): SUCCESS"
            ((SUCCESSFUL_WORKERS++))
        else
            echo "Worker ${i} (threshold=${THR}): FAILED"
            ((FAILED_WORKERS++))
        fi
    fi
done

echo "=============================================="
echo "log_density_max SWEEP COMPLETE"
echo "Successful: ${SUCCESSFUL_WORKERS}/4"
echo "After analysis: examine WandB project 'train_log_density_sweep_v2_phase0g'"
echo "  Compare across 4 runs by tag (thresh_neg2p0, thresh_0p0, thresh_1p0, thresh_3p0):"
echo "    - log_density_reg/max_log_density (peak)"
echo "    - log_density_reg/loss_term_epoch (did it actually fire?)"
echo "    - a_reg/max_a (final value — does the threshold help reduce sharpness?)"
echo "    - val_marginal_logdet (proxy for collapse — high = bad)"
echo "    - val_loss_epoch (negative NLL — collapse rewards low values, watch out)"
echo "=============================================="
date +"%Y-%m-%d %H:%M:%S"

for f in ${LOG_DIR}/slurm_logs/*_${SLURM_JOB_ID}.out; do
    [ -e "$f" ] && mv "$f" "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/" 2>/dev/null
done
for f in ${LOG_DIR}/slurm_logs/*_${SLURM_JOB_ID}.err; do
    [ -e "$f" ] && mv "$f" "${LOG_DIR}/slurm_logs/${SLURM_JOB_ID}/" 2>/dev/null
done

exit $FAILED_WORKERS
