scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/wind_forecasting_awaken_*_autoformer/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/
scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/wind_forecasting_awaken_*_informer/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/
scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/wind_forecasting_awaken_*_spacetimeformer/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/
scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/wind_forecasting_awaken_*_tactis/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/

scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/tuning_svr_aoifemac_awaken_pred*/"  /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/

scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/validation_results/InformerForecast/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/validation_results/
scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/validation_results/AutoformerForecast/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/validation_results/
scp -r ahenry@kestrel.hpc.nrel.gov:"/projects/awaken/ahenry/wind_forecasting/logging/validation_results/SpacetimeformerForecast/" /Users/ahenry/Documents/toolboxes/wind_forecasting/logging/validation_results/

rsync -auv ahenry@kestrel.hpc.nlr.gov:/projects/awaken/ahenry/whoc/floris_case_studies/{"baseline_controllers_perfect_forecaster_awaken","baseline_controllers_autoformer_forecasters_awaken","baseline_controllers_baseline_det_forecasters_awaken","baseline_controllers_baseline_prob_forecasters_awaken","baseline_controllers_informer_forecasters_awaken","baseline_controllers_spacetimeformer_forecasters_awaken","baseline_controllers_tactis_forecasters_awaken"} ./
rsync -auv ahenry@kestrel.hpc.nlr.gov:/projects/awaken/ahenry/wind_forecasting/logging/validation_results/{"AutoformerForecast","InformerForecast","KalmanFilterForecast","PersistenceForecast","SpacetimeformerForecast","SpatialFilterForecast","SVRForecast","TactisForecast"} ./
rsync -auv ahenry@kestrel.hpc.nlr.gov:/scratch/ahenry/kfs3-flash/{"awaken_processed_smoothed_normalized_train_ready_1s_all_turbine_ctx600_pred60_denormalize.parquet","awaken_processed_smoothed_normalized_train_ready_1s_all_turbine_ctx600_pred60_test_denormalize.parquet","awaken_processed_unsmoothed_normalized_train_ready_1s_all_turbine_ctx600_pred60_denormalize.parquet","awaken_processed_unsmoothed_normalized_train_ready_1s_all_turbine_ctx600_pred60_test_denormalize.parquet"} ./