config_label: "flasc_aoifemac"

filters:
  unresponsive_sensor:
    frozen_sensor_limit: 1200 # maximum duration for which a value can be constant before it is flagged as frozen, seconds
  range_flag:
    lower: 3
    upper: 25
  window_range_flag:
    window_start: 3
    window_end: 25
    value_min: 0.01 # factor multiplied by rated power
    value_max: 1.02 # factor multiplied by rated power
  bin_filter:
    bin_width: 100 # kW
    threshold: 1.5 # absolute deviation in wind speed 
    center_type: median
    bin_min: 0.01 # factor multiplied by rated power
    bin_max: 0.95 # factor multiplied by rated power
    threshold_type: scalar
  # nacelle_calibration:
  # std_range_flag:
  #   threshold: 1
  #   over: asset 
  #   r2_threshold: 0.89
  #   min_correlated_assets: 5
  # split:
  #   missing_col_thr: 4 # number of missing turbine measurements, from either wind speed or wind direction, (max = n_turbines) above which this subset of data will be omitted, i.e. if many data points are missing omit the data
  #   missing_duration_thr: 300 # maximum duration for which subsets of data which have missing measurements exceeding missing_col_thr in any feature type will still be included, i.e. if many data points are missing but only for a short time, use the data, seconds
  #   minimum_not_missing_duration: 1200 # minimum duration that any retained continuous subset of data must be to be useful, seconds, i.e. should contain at least the intended context length and prediction length
  impute_missing_data:
    r2_threshold: 0.7
  normalize:

feature_mapping:
  - time: time
    wind_direction: 'wind_direction_\d+_avg'
    wind_speed: 'wind_speed_\d+_avg'
    power_output: 'active_power_\d+_avg'
    nacelle_direction: 'nacelle_position_\d+_avg'

turbine_signature: 
  - '\d+'

turbine_mapping:
- 1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7

merge_chunk: 100
ram_limit: 75
frozen_sensor_limit: 1200 # maximum duration for which a value can be constant before it is flagged as frozen, seconds
missing_col_thr: 4 # number of missing turbine measurements, from either wind speed or wind direction, (max = n_turbines) above which this subset of data will be omitted, i.e. if many data points are missing omit the data
missing_duration_thr: 1200 # maximum duration for which subsets of data which have missing measurements exceeding missing_col_thr in any feature type will still be included, i.e. if many data points are missing but only for a short time, use the data, seconds
minimum_not_missing_duration: 1200 # minimum duration that any retained continuous subset of data must be to be useful, seconds, i.e. should contain at least the intended context length and prediction length
impute_r2_threshold: 0.7

nacelle_calibration_turbine_pairs:
- [0,1]
- [1,2]
- [3,4]
- [5,6]

dt: 60

raw_data_directory: 
  - /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/data/raw_flasc_data 
processed_data_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/data/preprocessed_flasc_data/SMARTEOLE_WakeSteering_SCADA_1minData.parquet
temp_storage_dir: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/data/preprocessed_flasc_data/temp
raw_data_file_signature: 
  - SMARTEOLE_WakeSteering_SCADA_1minData.csv
  
turbine_input_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/inputs/turbine_library/mm82.yaml
farm_input_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/inputs/smarteole_farm.yaml

# raw_data_directory: ~/wind-forecasting/examples/inputs/raw_flasc_data
# processed_data_path: ~/wind-forecasting/examples/inputs/SMARTEOLE-WFC-open-dataset/processed/SMARTEOLE_WakeSteering_SCADA_1minData.parquet
# turbine_input_path: ~/wind-forecasting/examples/inputs/turbine_library/mm82.yaml
# farm_input_path: ~/wind-forecasting/examples/inputs/smarteole_farm.yaml