config_label: rc_awaken_new

filters:
  unresponsive_sensor:
    frozen_sensor_limit: 1200 # maximum duration for which a value can be constant before it is flagged as frozen, seconds
  range_flag:
    lower: 3
    upper: 25
  window_range_flag:
    window_start: 3
    window_end: 25
    value_min: 0.01 # factor multiplied by rated power
    value_max: 1.02 # factor multiplied by rated power
  bin_filter:
    bin_width: 100 # kW
    threshold: 1.5 # absolute deviation in wind speed 
    center_type: median
    bin_min: 0.01 # factor multiplied by rated power
    bin_max: 0.95 # factor multiplied by rated power
    threshold_type: scalar
  nacelle_calibration:
  std_range_flag:
    threshold: 1
    over: asset 
    r2_threshold: 0.85
    min_correlated_assets: 5
  split:
    missing_col_thr: 66 # number of missing turbine measurements, from either wind speed or wind direction, (max = 2xn_turbines) above which this subset of data will be omitted, i.e. if many data points are missing omit the data
    missing_duration_thr: 300 # maximum duration for which subsets of data which have missing measurements exceeding missing_col_thr in any feature type will still be included, i.e. if many data points are missing but only for a short time, use the data, seconds
    minimum_not_missing_duration: 1200 # minimum duration that any retained continuous subset of data must be to be useful, seconds, i.e. should contain at least the intended context length and prediction length
  impute_missing_data:
    r2_threshold: 0.7
  normalize:

feature_mapping:
  - time: date
    turbine_id: turbine_id
    turbine_status: WTUR.TurSt
    wind_direction: WMET.HorWdDir
    wind_speed: WMET.HorWdSpd
    power_output: WTUR.W
    nacelle_direction: WNAC.Dir
  - time: '__index_level_0__'
    turbine_status: '[a-zA-Z0-9\_]+\.Turbine_State'
    yaw_offset_cw: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.wind_dev_1sec'
    wind_speed: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.WindSpeed'
    power_output: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.ActivePower'
    nacelle_direction: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.Nacelle_Position'

turbine_signature: 
  - 'wt\d{3}'
  - 'Turbine[A-Z][0-9]'

datetime_signature:
  - '\d{8}': '%Y%m%d'
  - '\d{8}.\d{6}': '%Y%m%d.%H%M%S'

turbine_mapping:
- wt001: 1
  wt002: 2
  wt003: 3
  wt004: 4
  wt005: 5
  wt006: 6
  wt007: 7
  wt008: 8
  wt009: 9
  wt010: 10
  wt011: 11
  wt012: 12
  wt013: 13
  wt014: 14
  wt015: 15
  wt016: 16
  wt017: 17
  wt018: 18
  wt019: 19
  wt020: 20
  wt021: 21
  wt022: 22
  wt023: 23
  wt024: 24
  wt025: 25
  wt026: 26
  wt027: 27
  wt028: 28
  wt029: 29
  wt030: 30
  wt031: 31
  wt032: 32
  wt033: 33
  wt034: 34
  wt035: 35
  wt036: 36
  wt037: 37
  wt038: 38
  wt039: 39
  wt040: 40
  wt041: 41
  wt042: 42
  wt043: 43
  wt044: 44
  wt045: 45
  wt046: 46
  wt047: 47
  wt048: 48
  wt049: 49
  wt050: 50
  wt051: 51
  wt052: 52
  wt053: 53
  wt054: 54
  wt055: 55
  wt056: 56
  wt057: 57
  wt058: 58
  wt059: 59
  wt060: 60
  wt061: 61
  wt062: 62
  wt063: 63
  wt064: 64
  wt065: 65
  wt066: 66
  wt067: 67
  wt068: 68
  wt069: 69
  wt070: 70
  wt071: 71
  wt072: 72
  wt073: 73
  wt074: 74
  wt075: 75
  wt076: 76
  wt077: 77
  wt078: 78
  wt079: 79
  wt080: 80
  wt081: 81
  wt082: 82
  wt083: 83
  wt084: 84
  wt085: 85
  wt086: 86
  wt087: 87
  wt088: 88
- TurbineA1: 1
  TurbineA2: 2
  TurbineA3: 3
  TurbineA4: 4
  TurbineA5: 5
  TurbineA6: 6
  TurbineA7: 7
  TurbineA8: 8
  TurbineA9: 9
  TurbineB1: 10
  TurbineB2: 11
  TurbineB3: 12
  TurbineB4: 13
  TurbineB5: 14
  TurbineB6: 15
  TurbineB7: 16
  TurbineB8: 17
  TurbineB9: 18
  TurbineC1: 19
  TurbineC2: 20
  TurbineC3: 21
  TurbineC4: 22
  TurbineC5: 23
  TurbineC6: 24
  TurbineC7: 25
  TurbineC8: 26
  TurbineC9: 27
  TurbineD1: 28
  TurbineD2: 29
  TurbineD3: 30
  TurbineD4: 31
  TurbineD5: 32
  TurbineD6: 33
  TurbineD7: 34
  TurbineD8: 35
  TurbineE1: 36
  TurbineE2: 37
  TurbineE3: 38
  TurbineE4: 39
  TurbineE5: 40
  TurbineE6: 41
  TurbineE7: 42
  TurbineE8: 43
  TurbineE9: 44
  TurbineF1: 45
  TurbineF2: 46
  TurbineF3: 47
  TurbineF4: 48
  TurbineF5: 49
  TurbineF6: 50
  TurbineF7: 51
  TurbineF8: 52
  TurbineF9: 53
  TurbineG1: 54
  TurbineG2: 55
  TurbineG3: 56
  TurbineG4: 57
  TurbineG5: 58
  TurbineG6: 59
  TurbineG7: 60
  TurbineG8: 61
  TurbineG9: 62
  TurbineH1: 63
  TurbineH2: 64
  TurbineH3: 65
  TurbineH4: 66
  TurbineH5: 67
  TurbineH6: 68
  TurbineH7: 69
  TurbineH8: 70
  TurbineH9: 71
  TurbineI1: 72
  TurbineI2: 73
  TurbineI3: 74
  TurbineI4: 75
  TurbineI5: 76
  TurbineI6: 77
  TurbineI7: 78
  TurbineI8: 79
  TurbineJ1: 80
  TurbineJ2: 81
  TurbineJ3: 82
  TurbineJ4: 83
  TurbineJ5: 84
  TurbineJ6: 85
  TurbineJ7: 86
  TurbineJ8: 87
  TurbineJ9: 88

merge_chunk: 1056
ram_limit: 70

#  [(61, 60), (51, 50), (43, 42), (41, 40), (18, 19), (34, 33), (17, 16), (22, 21) FLIPPED, (87, 86), (62, 63), (32, 33) POSSIBLY DROP, (59, 60), (43, 42) FLIPPED]
nacelle_calibration_turbine_pairs:
- [61,60]
- [51,50]
- [43,42]
- [41,40]
- [18,19]
- [34,33]
- [17,16]
- [22,21]
- [87,86]
- [62,63]
- [32,33]
- [59,60]

dt: 1

raw_data_directory: 
  - /pl/active/paolab/wind_forecasting/awaken_data/kp.turbine.z02.b0
  - /pl/active/paolab/wind_forecasting/awaken_data/00_engie_scada/

processed_data_path: /pl/active/paolab/wind_forecasting/awaken_data/awaken_processed.parquet 
temp_storage_dir: /tmp/scratch/$SLURM_JOB_ID/

raw_data_file_signature: 
  - kp.turbine.z02.b0.*.*.*.nc
  - ./**/KP_SCADA_*.*.parquet
  
turbine_input_path: /projects/aohe7145/toolboxes/wind_forecasting_env/wind-forecasting/examples/inputs/turbine_library/ge_282_127.yaml
farm_input_path: /projects/aohe7145/toolboxes/wind_forecasting_env/wind-forecasting/examples/inputs/gch_KP_v4.yaml