filters:
  - nacelle_calibration
  # - unresponsive_sensor
  # - range_flag
  - bin_filter
  # - std_range_flag
  # - impute_missing_data
  # - split
  # - normalize

feature_mapping:
  time: '__index_level_0__'
  turbine_status: '[a-zA-Z0-9\_]+\.Turbine_State'
  yaw_offset_cw: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.wind_dev_1sec'
  wind_speed: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.WindSpeed'
  power_output: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.ActivePower'
  nacelle_direction: '[a-zA-Z0-9\_]+\.[a-zA-Z0-9\_]+\.Nacelle_Position'

turbine_signature: 'Turbine[A-Z][0-9]'
datetime_signature:
  '\d{8}.\d{6}': '%Y%m%d.%H%M%S'

merge_chunk: 1000
ram_limit: 70
frozen_sensor_limit: 1200 # maximum duration for which a value can be constant before it is flagged as frozen, seconds
missing_col_thr: 66 # number of missing turbine measurements, from either wind speed or wind direction, (max = n_turbines) above which this subset of data will be omitted, i.e. if many data points are missing omit the data
missing_duration_thr: 300 # maximum duration for which subsets of data which have missing measurements exceeding missing_col_thr in any feature type will still be included, i.e. if many data points are missing but only for a short time, use the data, seconds
minimum_not_missing_duration: 1200 # minimum duration that any retained continuous subset of data must be to be useful, seconds, i.e. should contain at least the intended context length and prediction length
impute_r2_threshold: 0.7

nacelle_calibration_turbine_pairs:
- [51,50]
- [43,42]
- [41,40]
- [18,19]
- [34,33]
- [22,21]
- [87,86]
- [62,63]
- [33,32]
- [59,60]
- [43,42]

dt: 1

# raw_data_directory: /srv/data/nfs/scada/00_engie_scada
# processed_data_path: /srv/data/nfs/ahenry/preprocessed_awaken_data/filled_data.parquet
# turbine_input_path: /srv/data/nfs/ahenry/wind_forecasting_env/wind-forecasting/examples/inputs/ge_282_127.yaml
# farm_input_path: /srv/data/nfs/ahenry/wind_forecasting_env/wind-forecasting/examples/inputs/gch_KP_v4.yaml

raw_data_file_signature: KP_SCADA_*.*.parquet

raw_data_directory: /Users/ahenry/Downloads/00_engie_scada
processed_data_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/data/00_engie_scada_processed.parquet
raw_data_file_signature: ./**/KP_SCADA_*.*.parquet
turbine_input_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/inputs/turbine_library/ge_282_127.yaml
farm_input_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/inputs/gch_KP_v4.yaml